import React, { forwardRef } from "react";
import { Warning as AlertTriangleGlyph } from "@phosphor-icons/react/Warning";
import { ArrowDown as ArrowDownGlyph } from "@phosphor-icons/react/ArrowDown";
import { ArrowUp as ArrowUpGlyph } from "@phosphor-icons/react/ArrowUp";
import { Prohibit as BanGlyph } from "@phosphor-icons/react/Prohibit";
import { Bell as BellGlyph } from "@phosphor-icons/react/Bell";
import { BellSlash as BellOffGlyph } from "@phosphor-icons/react/BellSlash";
import { BookOpenText as BookOpenGlyph } from "@phosphor-icons/react/BookOpenText";
import { CalendarCheck as CalendarClockGlyph } from "@phosphor-icons/react/CalendarCheck";
import { CalendarDots as CalendarDaysGlyph } from "@phosphor-icons/react/CalendarDots";
import { Check as CheckGlyph } from "@phosphor-icons/react/Check";
import { CaretDown as ChevronDownGlyph } from "@phosphor-icons/react/CaretDown";
import { CaretLeft as ChevronLeftGlyph } from "@phosphor-icons/react/CaretLeft";
import { CaretRight as ChevronRightGlyph } from "@phosphor-icons/react/CaretRight";
import { Clock as ClockGlyph } from "@phosphor-icons/react/Clock";
import { Coffee as CoffeeGlyph } from "@phosphor-icons/react/Coffee";
import { Database as DatabaseBackupGlyph } from "@phosphor-icons/react/Database";
import { DownloadSimple as DownloadGlyph } from "@phosphor-icons/react/DownloadSimple";
import { Eye as EyeGlyph } from "@phosphor-icons/react/Eye";
import { EyeSlash as EyeOffGlyph } from "@phosphor-icons/react/EyeSlash";
import { Fire as FlameGlyph } from "@phosphor-icons/react/Fire";
import { GraduationCap as GraduationCapGlyph } from "@phosphor-icons/react/GraduationCap";
import { DotsSixVertical as GripVerticalGlyph } from "@phosphor-icons/react/DotsSixVertical";
import { ClockCounterClockwise as HistoryGlyph } from "@phosphor-icons/react/ClockCounterClockwise";
import { Key as KeyRoundGlyph } from "@phosphor-icons/react/Key";
import { Stack as LayersGlyph } from "@phosphor-icons/react/Stack";
import { Books as LibraryGlyph } from "@phosphor-icons/react/Books";
import { Link as Link2Glyph } from "@phosphor-icons/react/Link";
import { ListChecks as ListChecksGlyph } from "@phosphor-icons/react/ListChecks";
import { SignOut as LogOutGlyph } from "@phosphor-icons/react/SignOut";
import { EnvelopeSimple as MailGlyph } from "@phosphor-icons/react/EnvelopeSimple";
import { List as MenuGlyph } from "@phosphor-icons/react/List";
import { MoonStars as MoonGlyph } from "@phosphor-icons/react/MoonStars";
import { Notebook as NotebookTextGlyph } from "@phosphor-icons/react/Notebook";
import { Pause as PauseGlyph } from "@phosphor-icons/react/Pause";
import { PencilSimple as PencilGlyph } from "@phosphor-icons/react/PencilSimple";
import { Percent as PercentGlyph } from "@phosphor-icons/react/Percent";
import { Play as PlayGlyph } from "@phosphor-icons/react/Play";
import { Plus as PlusGlyph } from "@phosphor-icons/react/Plus";
import { ArrowsClockwise as RefreshCwGlyph } from "@phosphor-icons/react/ArrowsClockwise";
import { ArrowCounterClockwise as RotateCcwGlyph } from "@phosphor-icons/react/ArrowCounterClockwise";
import { ArrowClockwise as RotateCwGlyph } from "@phosphor-icons/react/ArrowClockwise";
import { MagnifyingGlass as SearchGlyph } from "@phosphor-icons/react/MagnifyingGlass";
import { GearSix as SettingsGlyph } from "@phosphor-icons/react/GearSix";
import { ShieldCheck as ShieldCheckGlyph } from "@phosphor-icons/react/ShieldCheck";
import { SlidersHorizontal as SlidersHorizontalGlyph } from "@phosphor-icons/react/SlidersHorizontal";
import { Compass as SparklesGlyph } from "@phosphor-icons/react/Compass";
import { Note as StickyNoteGlyph } from "@phosphor-icons/react/Note";
import { Sun as SunGlyph } from "@phosphor-icons/react/Sun";
import { Target as TargetGlyph } from "@phosphor-icons/react/Target";
import { Trash as Trash2Glyph } from "@phosphor-icons/react/Trash";
import { Trophy as TrophyGlyph } from "@phosphor-icons/react/Trophy";
import { UploadSimple as UploadGlyph } from "@phosphor-icons/react/UploadSimple";
import { User as UserGlyph } from "@phosphor-icons/react/User";
import { UserCircle as UserCircleGlyph } from "@phosphor-icons/react/UserCircle";
import { Users as UsersGlyph } from "@phosphor-icons/react/Users";
import { SpeakerHigh as Volume2Glyph } from "@phosphor-icons/react/SpeakerHigh";
import { SpeakerSlash as VolumeXGlyph } from "@phosphor-icons/react/SpeakerSlash";
import { X as XGlyph } from "@phosphor-icons/react/X";

// Keep icon styling consistent and import only the glyphs the app uses.
function icon(Glyph) {
  return forwardRef(function RotaIcon({ strokeWidth, weight = "duotone", ...props }, ref) {
    return <Glyph ref={ref} weight={weight} aria-hidden="true" {...props} />;
  });
}
export const AlertTriangle = icon(AlertTriangleGlyph);
export const ArrowDown = icon(ArrowDownGlyph);
export const ArrowUp = icon(ArrowUpGlyph);
export const Ban = icon(BanGlyph);
export const Bell = icon(BellGlyph);
export const BellOff = icon(BellOffGlyph);
export const BookOpen = icon(BookOpenGlyph);
export const CalendarClock = icon(CalendarClockGlyph);
export const CalendarDays = icon(CalendarDaysGlyph);
export const Check = icon(CheckGlyph);
export const ChevronDown = icon(ChevronDownGlyph);
export const ChevronLeft = icon(ChevronLeftGlyph);
export const ChevronRight = icon(ChevronRightGlyph);
export const Clock = icon(ClockGlyph);
export const Coffee = icon(CoffeeGlyph);
export const DatabaseBackup = icon(DatabaseBackupGlyph);
export const Download = icon(DownloadGlyph);
export const Eye = icon(EyeGlyph);
export const EyeOff = icon(EyeOffGlyph);
export const Flame = icon(FlameGlyph);
export const GraduationCap = icon(GraduationCapGlyph);
export const GripVertical = icon(GripVerticalGlyph);
export const History = icon(HistoryGlyph);
export const KeyRound = icon(KeyRoundGlyph);
export const Layers = icon(LayersGlyph);
export const Library = icon(LibraryGlyph);
export const Link2 = icon(Link2Glyph);
export const ListChecks = icon(ListChecksGlyph);
export const LogOut = icon(LogOutGlyph);
export const Mail = icon(MailGlyph);
export const Menu = icon(MenuGlyph);
export const Moon = icon(MoonGlyph);
export const NotebookText = icon(NotebookTextGlyph);
export const Pause = icon(PauseGlyph);
export const Pencil = icon(PencilGlyph);
export const Percent = icon(PercentGlyph);
export const Play = icon(PlayGlyph);
export const Plus = icon(PlusGlyph);
export const RefreshCw = icon(RefreshCwGlyph);
export const RotateCcw = icon(RotateCcwGlyph);
export const RotateCw = icon(RotateCwGlyph);
export const Search = icon(SearchGlyph);
export const Settings = icon(SettingsGlyph);
export const ShieldCheck = icon(ShieldCheckGlyph);
export const SlidersHorizontal = icon(SlidersHorizontalGlyph);
export const Sparkles = icon(SparklesGlyph);
export const StickyNote = icon(StickyNoteGlyph);
export const Sun = icon(SunGlyph);
export const Target = icon(TargetGlyph);
export const Trash2 = icon(Trash2Glyph);
export const Trophy = icon(TrophyGlyph);
export const Upload = icon(UploadGlyph);
export const User = icon(UserGlyph);
export const UserCircle = icon(UserCircleGlyph);
export const Users = icon(UsersGlyph);
export const Volume2 = icon(Volume2Glyph);
export const VolumeX = icon(VolumeXGlyph);
export const X = icon(XGlyph);
